kind: Service
apiVersion: v1
metadata:
  name: nima
  labels:
    app: nima
spec:
  type: NodePort
  selector:
    app: nima
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nima
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nima
  template:
    metadata:
      labels:
        app: nima
        version: v1
    spec:
      containers:
      - name: nima
        image: nima
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
